"""inisialisasi tabel pengguna dan prediksi

Revision ID: e8a487f3325c
Revises: 
Create Date: 2026-05-30 15:04:56.597156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a487f3325c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengguna',
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_pengguna'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prediksi',
    sa.Column('id_prediksi', sa.Integer(), nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('hasil', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id_pengguna'], ),
    sa.PrimaryKeyConstraint('id_prediksi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediksi')
    op.drop_table('pengguna')
    # ### end Alembic commands ###
